import React, { useState, useRef, useEffect, Fragment } from 'react'
// core components
import { Layout, LayoutContent, LayoutFooter, LayoutContainer, LayoutColumns, LayoutColumn } from '@paljs/ui/Layout'
import { DefaultTheme, ThemeProvider } from 'styled-components'
import { useRouter } from 'next/router'
import { Menu, MenuRefObject } from '@paljs/ui/Menu'
import { SidebarBody, SidebarRefObject, Sidebar } from '@paljs/ui/Sidebar'
import Header from './Header'
import Link from 'next/link'

import Image from 'next/image'
import { Row, Col } from 'react-bootstrap'
import menuItems from './menuItem'
import SimpleLayout from './SimpleLayout'
import SEO, { SEOProps } from '../components/SEO'
import themes from './themes'
import styles from '../pages/ezbets68/common.module.css'
import icons from '@paljs/icons'
import Head from 'next/head'
import { useStoreActions, useStoreState } from '../store/hooks'

const getDefaultTheme = (): DefaultTheme['name'] => {
  if (typeof localStorage !== 'undefined' && localStorage.getItem('theme')) {
    return localStorage.getItem('theme') as DefaultTheme['name']
  } else {
    const hours = new Date().getHours()
    return hours > 6 && hours < 19 ? 'default' : 'dark'
  }
}

export const MainLayout: React.FC<SEOProps> = ({ children, ...rest }): JSX.Element => {
  const [theme, setTheme] = useState<DefaultTheme['name']>('default')
  const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr')
  const sidebarRef = useRef<SidebarRefObject>(null)
  const router = useRouter()
  // const [menuState, setMenuState] = useState(false);
  const useRoute = useRouter()
  const { brand } = useRoute.query
  const menuRef = useRef<MenuRefObject>(null)
  const [seeHeader, setSeeHeader] = useState(true)
  const { commonUser } = useStoreState(state => state.commonUserStore)

  const getState = (state?: 'hidden' | 'visible' | 'compacted' | 'expanded') => {
    setSeeHeader(state !== 'compacted')
  }

  const changeTheme = (newTheme: DefaultTheme['name']) => {
    setTheme(newTheme)
    typeof localStorage !== 'undefined' && localStorage.setItem('theme', newTheme)
  }

  useEffect(() => {
    const localTheme = getDefaultTheme()
    if (localTheme !== theme && theme === 'default') {
      setTheme(localTheme)
    }
  }, [])

  const changeDir = () => {
    const newDir = dir === 'ltr' ? 'rtl' : 'ltr'
    setDir(newDir)
  }

  const authLayout = router.pathname.startsWith('/auth')

  const LayoutAttributes = {
    evaIcons: icons,
    dir: dir,
    className: !authLayout ? 'auth-layout' : '',
  }

  return (
    <>
      <SEO {...rest} />
      <ThemeProvider theme={themes(theme, dir)}>
        <Fragment>
          <SimpleLayout />

          <Layout {...LayoutAttributes}>
            <LayoutContainer>
              <Head>
                <title>{brand}</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
                <link rel='preconnect' href='https://fonts.googleapis.com' />
                <link rel='preconnect' href='https://fonts.gstatic.com' />
                <link rel='preconnect' href='https://fonts.googleapis.com' />
                <link rel='preconnect' href='https://fonts.gstatic.com' />
                <link
                  href='https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap'
                  rel='stylesheet'
                />
                <link href='https://fonts.googleapis.com/css2?family=Lato&display=swap' rel='stylesheet' />
              </Head>
              {!authLayout && (
                <Sidebar getState={getState} ref={sidebarRef} property='start' containerFixed responsive className={styles.menusidebar}>
                  {seeHeader && (
                    <header className={styles.userInfoHeader}>
                      <div className={styles.userInfo}>
                        <Row>
                          <Col className='col-3'>
                            <Image src='/images/user.png' alt='' height={77} width={56} />
                          </Col>
                          <Col className='col-9 d-flex align-items-center'>
                            <div className='font-weight-bold'>
                              <p className='mb-0 text-light font-18'>WELCOME BACK</p>
                              <p className='mb-0 text-light font-18'>{commonUser.fullName}</p>
                            </div>
                          </Col>
                        </Row>
                      </div>
                    </header>
                  )}
                  <SidebarBody>
                    <Menu
                      nextJs
                      className='sidebar-menu'
                      Link={Link}
                      ref={menuRef}
                      items={menuItems}
                      currentPath={router.pathname}
                      // toggleSidebar={() => sidebarRef.current?.hide()}
                    />
                    <div className='p-10 mt-6 cursor-pointer'>
                      <img src='/images/help_nav.png' alt='' />
                    </div>
                  </SidebarBody>
                </Sidebar>
              )}
              <LayoutContent>
                {!authLayout && (
                  <Header
                    dir={dir}
                    changeDir={changeDir}
                    theme={{ set: changeTheme, value: theme }}
                    toggleSidebar={() => sidebarRef.current?.toggle()}
                  />
                )}
                <LayoutColumns>
                  <LayoutColumn className={` ${styles.mainContent} main-content`}>
                    {children}
                    {!authLayout && <div className={` ${styles.main_layout_copy_right_text}`}>@ 2022, Made with BlockGaming Company️</div>}
                  </LayoutColumn>
                </LayoutColumns>
              </LayoutContent>
            </LayoutContainer>
          </Layout>
        </Fragment>
      </ThemeProvider>
    </>
  )
}
